apiVersion: apps/v1
kind: Deployment
metadata:
  name: Recipebook
spec:
  replicas: 2
  template:
    metadata:
      labels:
        type: amd64/linux
    spec:
      containers:
        - name: recipe-book
          image: arun7199/a64-client:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80